### ISSUE TITLE
Update PDF.js to 2.9

### ISSUE THREAD

**Issue by Zhechko** [agentcooper/react-pdf-highlighter#154]

**Comment by cbwchuck** [comment]
Would it be helpful to add `display: flex` to `.textLayer` in pdf_viewer.css?

**Comment by agentcooper** [comment]
@cbwchuck thanks, would you be able to open a PR with your suggestion?

**Comment by cbwchuck** [comment]
@agentcooper Sure! Only concern is I was looking into this issue with pdfjs-dist 2.11.338, not sure whether it will be too big a stride though :)

**Comment by holub008** [comment]
My team has noticed improvements in the text layer (fewer spacing issues) in master with pdf.js 2.11, coming from 2.8. Any ETA for next release? We can try to help out on any outstanding work that needs to be bundled with the release. Thank you both for the great work!

**Comment by agentcooper** [comment]
@holub008 Thanks for the reminder. I've released version 5.4.0. Could you please try it and send your feedback?

**Comment by holub008** [comment]
Awesome! Text selection quality is improved (the attached example would always be missing spaces because every word was wrapped in a span). I believe the improvement is due to [this update](https://github.com/mozilla/pdf.js/issues/7310#issuecomment-763897014).

I'm noticing an issue (also on the attached example) where some highlights go missing when doing multi-line selection. Not sure if that's `react-pdf-highlighter` or our app; I'll get back to you with what we find.

<img width="1414" alt="Screen Shot 2022-03-22 at 1 02 59 PM" src="https://user-images.githubusercontent.com/7282590/159547232-9984e9ba-bd7f-4406-9978-6dc229c6a04f.png">

**Comment by holub008** [comment]
I'm observing this problem even in the demo app - it seems to be limited to Firefox. I'll file an issue and investigate when I find more clues.

<img width="1397" alt="Screen Shot 2022-03-22 at 2 52 09 PM" src="https://user-images.githubusercontent.com/7282590/159565933-a13dfc08-68ca-400d-9b95-493ed66e2453.png">

**Comment by holub008** [comment]
Moving to https://github.com/agentcooper/react-pdf-highlighter/issues/180

**Comment by OscarBC** [comment]
I think I got it, Please see #181.

**Comment by agentcooper** [comment]
Closing as PDF.js was updated to 2.16.
