### ISSUE TITLE
Next.js support (use CSS modules)

### ISSUE THREAD

**Issue by agentcooper** [agentcooper/react-pdf-highlighter#156]
Most of work seems to be done by @Fensterbank in https://github.com/agentcooper/react-pdf-highlighter/issues/62#issuecomment-742059853.

It would be great if someone can send a PR based on that work.

Previous issues:
- #62
- #151

**Comment by rjuevesano** [comment]
any updates?

**Comment by Sydwelll** [comment]
any updates ?

**Comment by J0** [comment]
Hey,

Wondering where this issue at and if there's anything we can do to help push it along. Not too familiar with pdf.js atm but might have time to dive into it.

**Comment by SansPapyrus683** [comment]
Is there any PR that's going to address this soon?

**Comment by Jayraj-R** [comment]
Any update on this issue?

**Comment by GonzaGr92** [comment]
- For next < 14 you can use [next-transpile-modules](https://www.npmjs.com/package/next-transpile-modules) and in your next.config.js make the following:

``` 
const withTM = require('next-transpile-modules')(['react-pdf-highlighter']);

const nextConfig = {
  webpack: (config) => {
    config.resolve.alias.canvas = false;
  
    return config;
  },
}
 
module.exports = withTM(nextConfig)
``` 
(The webpack part is needed as a workaround of https://github.com/agentcooper/react-pdf-highlighter/issues/266)

- For next >= 14 transpilePackages was included as native https://nextjs.org/docs/app/api-reference/next-config-js/transpilePackages so should be the following:

``` 
const nextConfig = {
  transpilePackages: ['react-pdf-highlighter'],
  webpack: (config) => {
    config.resolve.alias.canvas = false;
  
    return config;
  },
}
 
module.exports = nextConfig
``` 

After that you should be able to consume the library as usual `import { PdfLoader } from "react-pdf-highlighter";`
Note: Is recommended to wrap all the logic into a component and consume it as dynamic or include 'use client' if you're using app router because it needs to run on the browser.
