### ISSUE TITLE
Any way to disable emojis?

### ISSUE THREAD

**Issue by riverole** [agentcooper/react-pdf-highlighter#44]
Hi,

First of all, thanks a lot for this library, it is pretty awesome. The only thing that I would like to tweak is to disable emojis on the comments. I have been checking around and I can hide the emojis that are being printed, but I cannot hide the input type emojis when adding the comment (there isn't any class or CSS selector that I can use as far as I know). Any way that we could disable them through a parameter in Tip or so? Thanks!

**Comment by agentcooper** [comment]
I don't think there is a way to disable those at the moment. My initial idea was that people will provide their custom `<Tip />` component if they want any customizations.

Feel free to send a PR with the added `className`.

**Comment by YuYanzy** [comment]
Hi! I've just solved this problem. Although a long time has passed since this issue was raised, I'll share my solution to help those who come after.
I have to say, the code design of this repo is very good.

To disable emojis, you just need to customize the `<Tip />` component.  The simplest way is to copy the original code of `<Tip / >` component, command out the emoji part,  and then import your customized `<Tip / >` component in your code.

Here is the original `<Tip />` component code: https://github1s.com/agentcooper/react-pdf-highlighter/blob/master/packages/react-pdf-highlighter/src/components/Tip.js

At last, thanks for such a  helpful project again! 👍 👍 👍

**Comment by axelraymundo** [comment]
If anyone wants to hide the emojis, just add this code in the style/App.css

`#PdfHighlighter__tip-container > div > form > div > div {
  display: none;
}`
