### ISSUE TITLE
Component  PdfLoader does not refresh when pdfFileUrl  changes

### ISSUE THREAD

**Issue by johnking** [agentcooper/react-pdf-highlighter#60]
I managed to set up an application based on the example of this repo with electron.js, I added a button to load new pdf files.  The highlight sidebar updates every time when I load a new pdf file and its associated annotations, but <PdfLoader> component does not refresh.

I tried to create a simple component such as

```js
const DemoComp = (props) => (
        <h2>{props.pdfFileUrl}</h2>
);
...       
{pdfFileUrl ? (
          <DemoComp pdfFileUrl={pdfFileUrl} />
) : null
```

the DemoComp updated as expected so the React state and its refresh cycle are working properly.

@agentcooper May you please give me some hints to resolve the issue?

thanks

**Comment by agentcooper** [comment]
I think this feature might be missing since there is only one case of `setDocument` (https://github.com/agentcooper/react-pdf-highlighter/blob/master/packages/react-pdf-highlighter/src/components/PdfHighlighter.js#L126) and it is in `componentDidMount`.

I will gladly accept a PR if you add `getDerivedStateFromProps` to `PdfHighlighter` that will trigger `setDocument` again.
